name: back-tests-workflow

on:
  pull_request

on:
  push:
    branches:
     - master

jobs:
  test-back:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
      - name: Use Node.js ${{ matrix.node-version }}
      - name: Goto back and run tests
        run: cd back && npm i && npm test